### ISSUE TITLE
Message error

### ISSUE THREAD

**Issue by EliseuFelipe** [signetlabdei/millicar#1]
Hi, can anyone tell me what is the meaning of this message error ? The scenario is simple, I just modified the vehicular-simple-one.cc a little bit. I just would like to know the cause of this message. Thank you. If the message persist I will post the code 

assert failed. cond="m_bid2lcid.find(bearerId) != m_bid2lcid.end()", msg="BearerId to LCID mapping not found ", file=../src/millicar/model/mmwave-vehicular-net-device.cc, line=408
terminate called without an active exception

**Comment by MatteoDrago** [comment]
HI @EliseuFelipe, 
thank you for your interest in MilliCar. As you may know, ns-3 is a quite detailed simulator and one error could be caused by many different factors. 
For this reason, without knowing which kind of changes you performed on vehicular-simple-one.cc, it is non trivial to guess what caused that specific error. I assume this is somehow related to #2, and I hope that my answer to that issue could help you as well. If that is not the case, please let us know.

**Comment by EliseuFelipe** [comment]
Hello @MatteoDrago , thank you for um reply. I realized that the error is when I try to install OLSR. I'm trying to make a connection between two nodes that are out of range with each other, Then I put a third node between them. Is it possible to do that using Millicar ?
